### ISSUE TITLE
FaceParser.ckpt is provided, but state.pt is required in the code. How to get state.pt

### ISSUE THREAD

**Issue by xiaozhang0927** [MartinPernus/MaskFaceGAN#11]
![image](https://user-images.githubusercontent.com/127761312/224728323-f18a1e7b-69b7-471e-88f8-6820e00c7451.png)
![image](https://user-images.githubusercontent.com/127761312/224728687-712ad4d0-b133-4e71-8c51-3356dbe88525.png)

**Comment by MartinPernus** [comment]
Hi! I will make sure to replace the 'FaceParser.ckpt', apparently I mistakenly uploaded the wrong checkpoint file. This file is a checkpoint generated by PyTorch Lightning.

An easy solution is to rename the ckpt file to 'state.pt', then insert `ckpt = ckpt['state_dict']` after `ckpt = torch.load()`. I will make sure to correct this soon.

**Comment by MartinPernus** [comment]
Fixed the checkpoint in fb75bb6, should be fine now.

**Comment by xiaozhang0927** [comment]
Thank you very much for your reply. I will try this method.
