### ISSUE TITLE
face alignment problem

### ISSUE THREAD

**Issue by royaloctave** [MartinPernus/MaskFaceGAN#3]
I tried to change hair in some images but the generated face is not aligned! it seems that we should do alignment before inputting the image to the algorithm. Can you please guide what is the right way to do it? would be nice to share if you have already scripts for it.

![A3B24690-10EE-49BE-BE35-687525A98818](https://user-images.githubusercontent.com/92549532/138462821-64bf626b-ac10-4d12-b00f-37cc34bfea4a.jpeg)
![59290BDF-C419-45E3-9FC4-FC2355C3C875](https://user-images.githubusercontent.com/92549532/138462844-31b2d3b2-2de6-44ba-a78a-3802042664e3.jpeg)
![1](https://user-images.githubusercontent.com/92549532/138462864-5224c724-f990-4cad-907f-5b7de4744194.jpeg)
![2](https://user-images.githubusercontent.com/92549532/138462872-8028c1ee-e81b-4e5b-83fe-63b44841fd66.jpeg)

As you see generated images have alignment issues!

**Comment by MartinPernus** [comment]
Hi,

the code to produce such images is available [here](https://github.com/mazzzystar/make-CelebA-HQ/blob/master/make_HQ_images.py), but requires 5 face landmarks. Those can be usually obtained by detector such as MTCNN. 

I have my own simple-to-use implementation that is based on the new RetinaFace detector landmarks. If you are willing to wait until Monday I can upload it.

**Comment by royaloctave** [comment]
Thanks. That would be great. Looking forward to it.

**Comment by MartinPernus** [comment]
I put together a repository for face extraction: [link](https://github.com/MartinPernus/FaceExtractor). If there are any issues, it's  probably best to open an issue there.
