### ISSUE TITLE
About the inference speed

### ISSUE THREAD

**Issue by SwordBearFire** [MartinPernus/MaskFaceGAN#5]
Hi, 

Thank you for publishing the amazing face edit repo. I got the exciting results, but the inference speed is very slow. Is it possible to process one image in a second? Thank you again.

Sincerely yours

**Comment by MartinPernus** [comment]
Hi, 

sorry, inference speed of this method cannot be under 1 second. The best way to speed it up is by using the E4E encoder to get a good initial latent code, but I have my doubts you can get good results when going below 30s/image.
